### ISSUE TITLE
Finish and Implement Text class

### ISSUE THREAD

**Issue by Reichenberg** [weweboom/Project_1#3]
you can claim this one sir

**Comment by DuncanTPerkins** [comment]
Hey man I think you can do assigns too. Try it out. I'm not sure if you can or not, but I think you can.

**Comment by Reichenberg** [comment]
Yeah, I can

**Comment by Reichenberg** [comment]
"This class should have at least two constructors – a default constructor and one that takes a string parameter representing the path/file name of the text file to be processed. "
We gotta change how text.cs works.
We can have the openFileDialog open in the Driver instead. Once that is fixed I can finish Words.cs. It's pretty much done.

**Comment by DuncanTPerkins** [comment]
I can fix that easy man you don't have to move anything outside of the Text class for that.

**Comment by Reichenberg** [comment]
I have to use it for words class which why I brought it up.

**Comment by DuncanTPerkins** [comment]
Look at the changes that I made in Text.cs

**Comment by Reichenberg** [comment]
I figure if he wants the path passed in he meant he wanted the driver to get the file path and have the text.cs use the streamreader

**Comment by Reichenberg** [comment]
I'm on my phone lol

**Comment by DuncanTPerkins** [comment]
Alright well look at it when you aren't on your phone then.
